---
name: GitHub Pages
on:
  workflow_dispatch: {}
  push:
    branches: [master]

  schedule:
    - cron: '30 2 * * *'    # Runs at 02:30 UTC every day

jobs:
  gh-pages:
    # Only run the job if the repository is section77/website
    if: github.repository == 'section77/website'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: generate site
        run: nix build .#site

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./result
